(()=>{'use strict';
let installPrompt=null,registration=null,registrationError='',requestedUpdate=false;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});
window.addEventListener('appinstalled',()=>{installPrompt=null;});
function offline(){let box=document.getElementById('chiayiConnection');if(!box){box=document.createElement('div');box.id='chiayiConnection';box.className='pwa-status';box.setAttribute('role','status');document.body.append(box);}box.hidden=navigator.onLine;box.textContent='目前離線：路徑規劃、天氣與交通需要連網';}
window.addEventListener('online',offline);window.addEventListener('offline',offline);
window.addEventListener('load',async()=>{offline();if('serviceWorker'in navigator&&window.isSecureContext){try{registration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){let b=document.getElementById('chiayiUpdateNotice');if(!b){b=document.createElement('button');b.id='chiayiUpdateNotice';b.className='pwa-status';b.textContent='有新版本，點此更新';b.onclick=applyUpdate;document.body.append(b);}}});});}catch{registrationError='無法啟用安裝更新服務，請確認 HTTPS 與 sw.js 的部署路徑。';}}});
async function applyUpdate(){if(window.chiayiNavigationActive){alert('請先結束導航再更新，以免中斷定位。');return;}if(!registration?.waiting){alert('目前沒有等待安裝的新版本。');return;}if(!confirm('更新將重新載入網站，目前未收藏的規劃狀態可能清除。立即更新？'))return;requestedUpdate=true;registration.waiting.postMessage({type:'ACTIVATE_UPDATE'});}
navigator.serviceWorker?.addEventListener('controllerchange',()=>{if(requestedUpdate)location.reload();});
window.ChiayiPWA={open(panel){const p=panel('📲 安裝與更新','');const text=document.createElement('p');text.textContent=registrationError||'可安裝到主畫面。離線時顯示連線提示；地圖、天氣、交通及路徑查詢仍需要網路。';p.append(text);const add=(label,fn)=>{const b=document.createElement('button');b.textContent=label;b.type='button';b.onclick=fn;p.append(b);};if(installPrompt)add('安裝嘉義樹導航',async()=>{await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;});else{const note=document.createElement('p');note.textContent=matchMedia('(display-mode: standalone)').matches?'已以安裝模式開啟。':'iPhone／iPad：用 Safari 開啟，點「分享」→「加入主畫面」。Android／電腦：在支援的瀏覽器選單選「安裝應用程式」。';p.append(note);}add('檢查更新',async()=>{try{if(!registration)throw Error('更新服務尚未就緒，請稍後重試。');await registration.update();text.textContent=registration.waiting?'新版本已準備好，請按「套用更新」。':registration.installing?'正在下載更新，完成後會顯示更新提示。':'目前沒有可用更新。';}catch(e){text.textContent=e.message;}});add('套用更新',applyUpdate);}};
})();
